on:
  pull_request:
#     types: [opened, synchronize, edited]
#     branches:
#       - master

jobs:
  create-changelog:
    name: changelog based on releases
    runs-on: ubuntu-latest
    steps:
      - name: Create Changelog
        id: create-change-log
        uses: velusgautam/changelog1/.github@main

      - uses: actions/checkout@v2

      - name: Simulate merged branch
        if: ${{ steps.create-change-log.outputs.changelog != '' }}
        run: |
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          git switch $GITHUB_HEAD_REF
          git checkout $GITHUB_BASE_REF CHANGELOG.md
          echo "${{steps.create-change-log.outputs.changelog}}" >> CHANGELOG.md
          git add CHANGELOG.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Changelog Commit"
          git push --set-upstream origin $GITHUB_HEAD_REF --no-verify
