# This workflow will read the PR to master branch and update the CHANGELOG.md file
# It reads the PR title and body and link any Jira Ticket form the jira keys.
# Then it pulls the latest CHANGELOG.md from master and append it with new body from PR
# Then it creates a new commit to the REF Branch where PR is made.

name: CHANGELOG

on:
  pull_request:
  # types: [opened, edited]
  # branches:
  #    - main
  # issue_comment:
  #  types: [created]
jobs:
  create-changelog:
    name: Changelog based on release PR
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get git logg diff
        id: merges
        shell: bash
        run: |
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git fetch origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          diff=$(git log $GITHUB_BASE_REF..$GITHUB_HEAD_REF --merges --pretty=format:"%b||" | sed '/^\s*$/d')
          echo "$diff"
          echo "::set-output name=logdiff::"$diff""

      - name: Using github scripts
        uses: actions/github-script@v4

        id: create-change-log
        env:
          DATA: ${{ steps.merges.outputs.logdiff }}
        with:
          script: |
            console.log("=========meregedCommits=========");
            console.log(process.env.DATA)

            const title = context.payload.pull_request.title;
            const jira_base = 'https://discoveryinc.atlassian.net/browse/'
            const fr_regex = /((?!(FR|fr)-?$){1}[FR0-9fr]+-\d+)/g;

            const body = process.env.DATA;
            const releaseBody = body.replace(/\|\|/g,"\n").replace(/"/g,"'");
            const releaseBodyWithJiraLinks = releaseBody.replace(fr_regex, jira_key =>`[${jira_key}](${jira_base}${jira_key})`)
            const releaseLog = `
            ## ${title}

            ${releaseBodyWithJiraLinks}
            `;

            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: context.payload.pull_request.title,
              body: `
              ${releaseBodyWithJiraLinks}
              `
            };
        
            const response = await github.pulls.update(request);

            core.info(`Response: ${response.status}`);
            if (response.status !== 200) {
              core.error('Updating the pull request has failed');
            }

            core.setOutput('changelog', releaseLog);

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Create changelog commit
        if: ${{ steps.create-change-log.outputs.changelog != '' }}
        run: |
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          git switch $GITHUB_HEAD_REF
          git checkout $GITHUB_BASE_REF CHANGELOG.md
          echo "${{steps.create-change-log.outputs.changelog}}" >> CHANGELOG.md
          git add CHANGELOG.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Changelog Commit"
          git push --set-upstream origin $GITHUB_HEAD_REF --no-verify
