name: changelog-builder

on: 
  pull_request:
    branches:
      - main

env: 
  CI: true
  FORCE_COLOR: 3

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

       - name: Simulate merge branch
         run: |
          echo "$(github.event.pull_request.comment)"
