on:
  pull_request:
    types: [closed]

jobs:
  sync-changelog:
    name: sync changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: sync changelog
        id: create-change-log
        run: |
          echo "Starts"
          CLONE_DIR=$(mktemp -d)
          DESTINATION_REPOSITORY_USERNAME=velusgautam
          DESTINATION_REPOSITORY_NAME=changelogs
          API_TOKEN_GITHUB=${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH=main

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git clone --single-branch --branch main "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git" "$CLONE_DIR"
          ls -la "$CLONE_DIR"

          TARGET_BASE=$(mktemp -d)
          TARGET_DIRECTORY=sonic-studio

          mv "$CLONE_DIR/.git" "$TARGET_BASE"

          echo "Copy contents to target git repository"
          mkdir -p "$TARGET_BASE"/"$TARGET_DIRECTORY"
          cp ./CHANGELOG.md "$TARGET_BASE"/"$TARGET_DIRECTORY"
          cd "$TARGET_BASE"

          echo "git add:"
          git add .

          echo "git status:"
          git status

          echo "git diff-index:"
          git diff-index --quiet HEAD || git commit --message "SYNC CHANGELOG"

          echo "git push origin:"
          git push origin --set-upstream "$TARGET_BRANCH"




          # git remote add destination git@github.com:velusgautam/changelogs.git
          # git fetch destination main:main
          # git switch destination/main
          # git checkout destination/main sonic-studio/CHANGELOG.md
          # echo "${{steps.create-change-log.outputs.changelog}}" >> sonic-studio/CHANGELOG.md
          # git add sonic-studio/CHANGELOG.md
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git commit -m "Changelog Commit"
          # git push --set-upstream destination main --no-verify -f
