name: SYNC CHANGELOG
on:
  pull_request:
    types: [closed]

jobs:
  sync-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: sync changelog
        run: |
          echo "START SYNC"
          CLONE_DIR=$(mktemp -d)
          DESTINATION_REPOSITORY_NAME=velusgautam/changelogs
          API_TOKEN_GITHUB=${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH=main
          TARGET_BASE=$(mktemp -d)
          TARGET_DIRECTORY=${{ github.event.repository.name }}

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git clone --single-branch --branch main "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_REPOSITORY_NAME.git" "$CLONE_DIR"
          ls -la "$CLONE_DIR"

          mv "$CLONE_DIR/*" "$TARGET_BASE"

          echo "Copy contents to target git repository"
          mkdir -p "$TARGET_BASE"/"$TARGET_DIRECTORY"
          cp ./CHANGELOG.md "$TARGET_BASE"/"$TARGET_DIRECTORY"
          cd "$TARGET_BASE"

          echo "git add:"
          git add .

          echo "git status:"
          git status

          echo "git diff-index:"
          git diff-index --quiet HEAD || git commit --message "SYNC CHANGELOG"

          echo "git push origin:"
          git push origin --set-upstream "$TARGET_BRANCH"
