on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: velusgautam/changelog1@main
        with:
          who-to-greet: 'Mona the Octocat'

      - uses: actions/checkout@v2

      - name: Simulate merged branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git init
          git switch $GITHUB_HEAD_REF
          git add CHANGELOG.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Changelog Commit"
          git remote add origin git@github.com:velusgautam/changelogs.git
          git push origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF

      # Use the output from the `hello` step
